//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VmManager.Properties {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VmManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Manager.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Manager.
        /// </summary>
        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Manager Setup.
        /// </summary>
        public static string AppSetupTitle {
            get {
                return ResourceManager.GetString("AppSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string Nav_Marketplace {
            get {
                return ResourceManager.GetString("Nav_Marketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My VMs.
        /// </summary>
        public static string Nav_MyVms {
            get {
                return ResourceManager.GetString("Nav_MyVms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project on GitHub.
        /// </summary>
        public static string Tooltip_OpenGitHub {
            get {
                return ResourceManager.GetString("Tooltip_OpenGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Image Sources settings.
        /// </summary>
        public static string Tooltip_GoToImageSources {
            get {
                return ResourceManager.GetString("Tooltip_GoToImageSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Tooltip_Refresh {
            get {
                return ResourceManager.GetString("Tooltip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string Tooltip_CopyToClipboard {
            get {
                return ResourceManager.GetString("Tooltip_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy username.
        /// </summary>
        public static string Tooltip_CopyUsername {
            get {
                return ResourceManager.GetString("Tooltip_CopyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password.
        /// </summary>
        public static string Tooltip_CopyPassword {
            get {
                return ResourceManager.GetString("Tooltip_CopyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename this VM.
        /// </summary>
        public static string Tooltip_RenameVm {
            get {
                return ResourceManager.GetString("Tooltip_RenameVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires the VM to be turned off.
        /// </summary>
        public static string Tooltip_RenameRequiresOff {
            get {
                return ResourceManager.GetString("Tooltip_RenameRequiresOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete this VM.
        /// </summary>
        public static string Tooltip_DeleteVm {
            get {
                return ResourceManager.GetString("Tooltip_DeleteVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete snapshot.
        /// </summary>
        public static string Tooltip_DeleteSnapshot {
            get {
                return ResourceManager.GetString("Tooltip_DeleteSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this feed.
        /// </summary>
        public static string Tooltip_RemoveFeed {
            get {
                return ResourceManager.GetString("Tooltip_RemoveFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Tooltip_Delete {
            get {
                return ResourceManager.GetString("Tooltip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My VMs.
        /// </summary>
        public static string MyVms_PageTitle {
            get {
                return ResourceManager.GetString("MyVms_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MyVms_Start {
            get {
                return ResourceManager.GetString("MyVms_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string MyVms_Stop {
            get {
                return ResourceManager.GetString("MyVms_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string MyVms_Connect {
            get {
                return ResourceManager.GetString("MyVms_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string MyVms_Rename {
            get {
                return ResourceManager.GetString("MyVms_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string MyVms_Restore {
            get {
                return ResourceManager.GetString("MyVms_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string MyVms_Clone {
            get {
                return ResourceManager.GetString("MyVms_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string MyVms_Push {
            get {
                return ResourceManager.GetString("MyVms_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string MyVms_Create {
            get {
                return ResourceManager.GetString("MyVms_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to base.
        /// </summary>
        public static string MyVms_ResetToBase {
            get {
                return ResourceManager.GetString("MyVms_ResetToBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots.
        /// </summary>
        public static string MyVms_Snapshots {
            get {
                return ResourceManager.GetString("MyVms_Snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading VMs....
        /// </summary>
        public static string MyVms_LoadingVms {
            get {
                return ResourceManager.GetString("MyVms_LoadingVms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No virtual machines found.
        /// </summary>
        public static string MyVms_NoVmsFound {
            get {
                return ResourceManager.GetString("MyVms_NoVmsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import an image from the Images page to get started..
        /// </summary>
        public static string MyVms_NoVmsHint {
            get {
                return ResourceManager.GetString("MyVms_NoVmsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        public static string MyVms_Troubleshoot {
            get {
                return ResourceManager.GetString("MyVms_Troubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VM backend is not available.
        /// </summary>
        public static string MyVms_BackendUnavailable {
            get {
                return ResourceManager.GetString("MyVms_BackendUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default credentials.
        /// </summary>
        public static string MyVms_DefaultCredentials {
            get {
                return ResourceManager.GetString("MyVms_DefaultCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string MyVms_User {
            get {
                return ResourceManager.GetString("MyVms_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string MyVms_Password {
            get {
                return ResourceManager.GetString("MyVms_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from .
        /// </summary>
        public static string MyVms_From {
            get {
                return ResourceManager.GetString("MyVms_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add notes....
        /// </summary>
        public static string MyVms_NotesPlaceholder {
            get {
                return ResourceManager.GetString("MyVms_NotesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot name....
        /// </summary>
        public static string MyVms_SnapshotNamePlaceholder {
            get {
                return ResourceManager.GetString("MyVms_SnapshotNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime: {0:hh\:mm\:ss}.
        /// </summary>
        public static string MyVms_UptimeFormat {
            get {
                return ResourceManager.GetString("MyVms_UptimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string Images_PageTitle {
            get {
                return ResourceManager.GetString("Images_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search images....
        /// </summary>
        public static string Images_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Images_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Images_Import {
            get {
                return ResourceManager.GetString("Images_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create VM.
        /// </summary>
        public static string Images_CreateVm {
            get {
                return ResourceManager.GetString("Images_CreateVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-import.
        /// </summary>
        public static string Images_ReImport {
            get {
                return ResourceManager.GetString("Images_ReImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Images_Cancel {
            get {
                return ResourceManager.GetString("Images_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Images.
        /// </summary>
        public static string Images_LocalImages {
            get {
                return ResourceManager.GetString("Images_LocalImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Snapshots.
        /// </summary>
        public static string Images_SharedSnapshots {
            get {
                return ResourceManager.GetString("Images_SharedSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snapshot.
        /// </summary>
        public static string Images_SnapshotBadge {
            get {
                return ResourceManager.GetString("Images_SnapshotBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading catalog....
        /// </summary>
        public static string Images_LoadingCatalog {
            get {
                return ResourceManager.GetString("Images_LoadingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image sources configured.
        /// </summary>
        public static string Images_NoSourcesConfigured {
            get {
                return ResourceManager.GetString("Images_NoSourcesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings to configure an OCI registry, Nexus, or local catalog path..
        /// </summary>
        public static string Images_NoSourcesHint {
            get {
                return ResourceManager.GetString("Images_NoSourcesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images found.
        /// </summary>
        public static string Images_NoImagesFound {
            get {
                return ResourceManager.GetString("Images_NoImagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push images to your registry, or check your search filters..
        /// </summary>
        public static string Images_NoImagesHint {
            get {
                return ResourceManager.GetString("Images_NoImagesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Sources.
        /// </summary>
        public static string Settings_ImageSources {
            get {
                return ResourceManager.GetString("Settings_ImageSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feed.
        /// </summary>
        public static string Settings_AddFeed {
            get {
                return ResourceManager.GetString("Settings_AddFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed name.
        /// </summary>
        public static string Settings_FeedNamePlaceholder {
            get {
                return ResourceManager.GetString("Settings_FeedNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL or path.
        /// </summary>
        public static string Settings_UrlPlaceholder {
            get {
                return ResourceManager.GetString("Settings_UrlPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Settings_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Settings_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string Settings_TestConnection {
            get {
                return ResourceManager.GetString("Settings_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Settings_Discover {
            get {
                return ResourceManager.GetString("Settings_Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Defaults.
        /// </summary>
        public static string Settings_VmDefaults {
            get {
                return ResourceManager.GetString("Settings_VmDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory: .
        /// </summary>
        public static string Settings_Memory {
            get {
                return ResourceManager.GetString("Settings_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MB.
        /// </summary>
        public static string Settings_MemoryUnit {
            get {
                return ResourceManager.GetString("Settings_MemoryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU: .
        /// </summary>
        public static string Settings_Cpu {
            get {
                return ResourceManager.GetString("Settings_Cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cores.
        /// </summary>
        public static string Settings_CpuUnit {
            get {
                return ResourceManager.GetString("Settings_CpuUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Username.
        /// </summary>
        public static string Settings_DefaultUsername {
            get {
                return ResourceManager.GetString("Settings_DefaultUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Password.
        /// </summary>
        public static string Settings_DefaultPassword {
            get {
                return ResourceManager.GetString("Settings_DefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Administrator.
        /// </summary>
        public static string Settings_UsernameSample {
            get {
                return ResourceManager.GetString("Settings_UsernameSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Admin123!.
        /// </summary>
        public static string Settings_PasswordSample {
            get {
                return ResourceManager.GetString("Settings_PasswordSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local VM Storage.
        /// </summary>
        public static string Settings_LocalVmStorage {
            get {
                return ResourceManager.GetString("Settings_LocalVmStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. C:\VMs.
        /// </summary>
        public static string Settings_LocalVmPathSample {
            get {
                return ResourceManager.GetString("Settings_LocalVmPathSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Settings_Browse {
            get {
                return ResourceManager.GetString("Settings_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale Settings.
        /// </summary>
        public static string Settings_LocaleSettings {
            get {
                return ResourceManager.GetString("Settings_LocaleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply locale and keyboard layout after VM creation.
        /// </summary>
        public static string Settings_ApplyLocale {
            get {
                return ResourceManager.GetString("Settings_ApplyLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        public static string Settings_Locale {
            get {
                return ResourceManager.GetString("Settings_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Layout.
        /// </summary>
        public static string Settings_KeyboardLayout {
            get {
                return ResourceManager.GetString("Settings_KeyboardLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Creation.
        /// </summary>
        public static string Settings_PostCreation {
            get {
                return ResourceManager.GetString("Settings_PostCreation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename computer to VM name after creation.
        /// </summary>
        public static string Settings_RenameComputer {
            get {
                return ResourceManager.GetString("Settings_RenameComputer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PowerShell script to run after VM creation.
        /// </summary>
        public static string Settings_PostCreationScript {
            get {
                return ResourceManager.GetString("Settings_PostCreationScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. winget install TeamViewer.TeamViewer.Host --silent.
        /// </summary>
        public static string Settings_PostCreationScriptPlaceholder {
            get {
                return ResourceManager.GetString("Settings_PostCreationScriptPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string Settings_Saved {
            get {
                return ResourceManager.GetString("Settings_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save: {0}.
        /// </summary>
        public static string Settings_SaveFailedFormat {
            get {
                return ResourceManager.GetString("Settings_SaveFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Settings_Remove {
            get {
                return ResourceManager.GetString("Settings_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Local VMs Folder.
        /// </summary>
        public static string Settings_SelectVmFolder {
            get {
                return ResourceManager.GetString("Settings_SelectVmFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing....
        /// </summary>
        public static string Settings_Testing {
            get {
                return ResourceManager.GetString("Settings_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Settings_Connected {
            get {
                return ResourceManager.GetString("Settings_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreachable.
        /// </summary>
        public static string Settings_Unreachable {
            get {
                return ResourceManager.GetString("Settings_Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: {0}.
        /// </summary>
        public static string Settings_ConnectionFailedFormat {
            get {
                return ResourceManager.GetString("Settings_ConnectionFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering repositories....
        /// </summary>
        public static string Settings_Discovering {
            get {
                return ResourceManager.GetString("Settings_Discovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} repositor{1} found.
        /// </summary>
        public static string Settings_ReposFoundFormat {
            get {
                return ResourceManager.GetString("Settings_ReposFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Feed.
        /// </summary>
        public static string Settings_NewFeedName {
            get {
                return ResourceManager.GetString("Settings_NewFeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Dialog_Push {
            get {
                return ResourceManager.GetString("Dialog_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Dialog_Rename {
            get {
                return ResourceManager.GetString("Dialog_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename VM.
        /// </summary>
        public static string Dialog_RenameVm {
            get {
                return ResourceManager.GetString("Dialog_RenameVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string Dialog_NewName {
            get {
                return ResourceManager.GetString("Dialog_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Push Target.
        /// </summary>
        public static string Dialog_SelectPushTarget {
            get {
                return ResourceManager.GetString("Dialog_SelectPushTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This VM has no linked feed. Choose where to push:.
        /// </summary>
        public static string Dialog_NoPushFeedMessage {
            get {
                return ResourceManager.GetString("Dialog_NoPushFeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Dialog_Back {
            get {
                return ResourceManager.GetString("Dialog_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Dialog_Next {
            get {
                return ResourceManager.GetString("Dialog_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Dialog_Finish {
            get {
                return ResourceManager.GetString("Dialog_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Repository.
        /// </summary>
        public static string Dialog_SelectRepository {
            get {
                return ResourceManager.GetString("Dialog_SelectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feed has multiple repositories. Choose where to push:.
        /// </summary>
        public static string Dialog_SelectRepositoryMessage {
            get {
                return ResourceManager.GetString("Dialog_SelectRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Dialog_Select {
            get {
                return ResourceManager.GetString("Dialog_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot Name.
        /// </summary>
        public static string Dialog_SnapshotName {
            get {
                return ResourceManager.GetString("Dialog_SnapshotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name your VM.
        /// </summary>
        public static string Dialog_NameYourVm {
            get {
                return ResourceManager.GetString("Dialog_NameYourVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy failed.
        /// </summary>
        public static string Dialog_CopyFailed {
            get {
                return ResourceManager.GetString("Dialog_CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to VM Manager.
        /// </summary>
        public static string Wizard_WelcomeTitle {
            get {
                return ResourceManager.GetString("Wizard_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, manage, and share virtual machines with your team..
        /// </summary>
        public static string Wizard_WelcomeSubtitle {
            get {
                return ResourceManager.GetString("Wizard_WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will help you configure your VM storage location, default settings, .
        /// </summary>
        public static string Wizard_WelcomeDescription {
            get {
                return ResourceManager.GetString("Wizard_WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Defaults.
        /// </summary>
        public static string Wizard_VmDefaults {
            get {
                return ResourceManager.GetString("Wizard_VmDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure default settings for new virtual machines..
        /// </summary>
        public static string Wizard_VmDefaultsDescription {
            get {
                return ResourceManager.GetString("Wizard_VmDefaultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Storage Path.
        /// </summary>
        public static string Wizard_VmStoragePath {
            get {
                return ResourceManager.GetString("Wizard_VmStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply locale after VM creation.
        /// </summary>
        public static string Wizard_ApplyLocale {
            get {
                return ResourceManager.GetString("Wizard_ApplyLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        public static string Wizard_Locale {
            get {
                return ResourceManager.GetString("Wizard_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Wizard_Keyboard {
            get {
                return ResourceManager.GetString("Wizard_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Sources.
        /// </summary>
        public static string Wizard_ImageSources {
            get {
                return ResourceManager.GetString("Wizard_ImageSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure where to pull VM images from. You can add more later in Settings..
        /// </summary>
        public static string Wizard_ImageSourcesDescription {
            get {
                return ResourceManager.GetString("Wizard_ImageSourcesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can skip this step and configure feeds later in Settings..
        /// </summary>
        public static string Wizard_SkipHint {
            get {
                return ResourceManager.GetString("Wizard_SkipHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of 3.
        /// </summary>
        public static string Wizard_StepFormat {
            get {
                return ResourceManager.GetString("Wizard_StepFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend: Checking....
        /// </summary>
        public static string Status_BackendChecking {
            get {
                return ResourceManager.GetString("Status_BackendChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker: Checking....
        /// </summary>
        public static string Status_DockerChecking {
            get {
                return ResourceManager.GetString("Status_DockerChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker: Available.
        /// </summary>
        public static string Status_DockerAvailable {
            get {
                return ResourceManager.GetString("Status_DockerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker: Not installed.
        /// </summary>
        public static string Status_DockerNotInstalled {
            get {
                return ResourceManager.GetString("Status_DockerNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds: checking....
        /// </summary>
        public static string Status_FeedsChecking {
            get {
                return ResourceManager.GetString("Status_FeedsChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feeds configured.
        /// </summary>
        public static string Status_NoFeedsConfigured {
            get {
                return ResourceManager.GetString("Status_NoFeedsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds: {0} configured.
        /// </summary>
        public static string Status_FeedsConfiguredFormat {
            get {
                return ResourceManager.GetString("Status_FeedsConfiguredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Manager v{0}.{1}.{2}.
        /// </summary>
        public static string Status_VersionFormat {
            get {
                return ResourceManager.GetString("Status_VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running diagnostics....
        /// </summary>
        public static string Status_RunningDiagnostics {
            get {
                return ResourceManager.GetString("Status_RunningDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot failed: {0}.
        /// </summary>
        public static string Status_TroubleshootFailedFormat {
            get {
                return ResourceManager.GetString("Status_TroubleshootFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking available RAM for {0}....
        /// </summary>
        public static string Status_CheckingRamFormat {
            get {
                return ResourceManager.GetString("Status_CheckingRamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}....
        /// </summary>
        public static string Status_StartingFormat {
            get {
                return ResourceManager.GetString("Status_StartingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started..
        /// </summary>
        public static string Status_StartedFormat {
            get {
                return ResourceManager.GetString("Status_StartedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping {0}....
        /// </summary>
        public static string Status_StoppingFormat {
            get {
                return ResourceManager.GetString("Status_StoppingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stopped..
        /// </summary>
        public static string Status_StoppedFormat {
            get {
                return ResourceManager.GetString("Status_StoppedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}....
        /// </summary>
        public static string Status_DeletingFormat {
            get {
                return ResourceManager.GetString("Status_DeletingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted..
        /// </summary>
        public static string Status_DeletedFormat {
            get {
                return ResourceManager.GetString("Status_DeletedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}....
        /// </summary>
        public static string Status_ConnectingFormat {
            get {
                return ResourceManager.GetString("Status_ConnectingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming {0}....
        /// </summary>
        public static string Status_RenamingFormat {
            get {
                return ResourceManager.GetString("Status_RenamingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed to {0}..
        /// </summary>
        public static string Status_RenamedFormat {
            get {
                return ResourceManager.GetString("Status_RenamedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating snapshot of {0}....
        /// </summary>
        public static string Status_CreatingSnapshotFormat {
            get {
                return ResourceManager.GetString("Status_CreatingSnapshotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot &quot;{0}&quot; created..
        /// </summary>
        public static string Status_SnapshotCreatedFormat {
            get {
                return ResourceManager.GetString("Status_SnapshotCreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping {0}....
        /// </summary>
        public static string Status_RestoringFormat {
            get {
                return ResourceManager.GetString("Status_RestoringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying snapshot &quot;{0}&quot;....
        /// </summary>
        public static string Status_ApplyingSnapshotFormat {
            get {
                return ResourceManager.GetString("Status_ApplyingSnapshotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing VM list....
        /// </summary>
        public static string Status_RefreshingVmList {
            get {
                return ResourceManager.GetString("Status_RefreshingVmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored to &quot;{0}&quot;..
        /// </summary>
        public static string Status_RestoredFormat {
            get {
                return ResourceManager.GetString("Status_RestoredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting {0} to base image....
        /// </summary>
        public static string Status_ResettingFormat {
            get {
                return ResourceManager.GetString("Status_ResettingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreating disk for {0}....
        /// </summary>
        public static string Status_RecreatingDiskFormat {
            get {
                return ResourceManager.GetString("Status_RecreatingDiskFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reset to base image..
        /// </summary>
        public static string Status_ResetCompleteFormat {
            get {
                return ResourceManager.GetString("Status_ResetCompleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting snapshot &quot;{0}&quot; for cloning....
        /// </summary>
        public static string Status_ExportingSnapshotFormat {
            get {
                return ResourceManager.GetString("Status_ExportingSnapshotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new VM &quot;{0}&quot; from snapshot &quot;{1}&quot;..
        /// </summary>
        public static string Status_ClonedFormat {
            get {
                return ResourceManager.GetString("Status_ClonedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing to {0}....
        /// </summary>
        public static string Status_PushingToFormat {
            get {
                return ResourceManager.GetString("Status_PushingToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot &quot;{0}&quot; pushed to {1}..
        /// </summary>
        public static string Status_PushCompleteFormat {
            get {
                return ResourceManager.GetString("Status_PushCompleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting &quot;{0}&quot;....
        /// </summary>
        public static string Status_DeletingSnapshotFormat {
            get {
                return ResourceManager.GetString("Status_DeletingSnapshotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot &quot;{0}&quot; deleted..
        /// </summary>
        public static string Status_SnapshotDeletedFormat {
            get {
                return ResourceManager.GetString("Status_SnapshotDeletedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &quot;{0}&quot;?.
        /// </summary>
        public static string Confirm_DeleteTitleFormat {
            get {
                return ResourceManager.GetString("Confirm_DeleteTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will permanently remove the {0}..
        /// </summary>
        public static string Confirm_DeleteVmFormat {
            get {
                return ResourceManager.GetString("Confirm_DeleteVmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to container.
        /// </summary>
        public static string Confirm_DeleteContainerType {
            get {
                return ResourceManager.GetString("Confirm_DeleteContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM.
        /// </summary>
        public static string Confirm_DeleteVmType {
            get {
                return ResourceManager.GetString("Confirm_DeleteVmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore to &quot;{0}&quot;?.
        /// </summary>
        public static string Confirm_RestoreTitleFormat {
            get {
                return ResourceManager.GetString("Confirm_RestoreTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will stop the VM and restore it to this snapshot..
        /// </summary>
        public static string Confirm_RestoreMessage {
            get {
                return ResourceManager.GetString("Confirm_RestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &quot;{0}&quot; to base image?.
        /// </summary>
        public static string Confirm_ResetTitleFormat {
            get {
                return ResourceManager.GetString("Confirm_ResetTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will stop the VM and discard all changes since it was created..
        /// </summary>
        public static string Confirm_ResetMessage {
            get {
                return ResourceManager.GetString("Confirm_ResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete snapshot &quot;{0}&quot;?.
        /// </summary>
        public static string Confirm_DeleteSnapshotTitleFormat {
            get {
                return ResourceManager.GetString("Confirm_DeleteSnapshotTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cannot be undone..
        /// </summary>
        public static string Confirm_DeleteSnapshotMessage {
            get {
                return ResourceManager.GetString("Confirm_DeleteSnapshotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect: {0}.
        /// </summary>
        public static string Error_ConnectFailedFormat {
            get {
                return ResourceManager.GetString("Error_ConnectFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load snapshots: {0}.
        /// </summary>
        public static string Error_SnapshotsFailedFormat {
            get {
                return ResourceManager.GetString("Error_SnapshotsFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;Base&quot; is reserved for the initial VM state..
        /// </summary>
        public static string Error_BaseNameReserved {
            get {
                return ResourceManager.GetString("Error_BaseNameReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot failed: {0}.
        /// </summary>
        public static string Error_SnapshotFailedFormat {
            get {
                return ResourceManager.GetString("Error_SnapshotFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore failed: {0}.
        /// </summary>
        public static string Error_RestoreFailedFormat {
            get {
                return ResourceManager.GetString("Error_RestoreFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset failed: {0}.
        /// </summary>
        public static string Error_ResetFailedFormat {
            get {
                return ResourceManager.GetString("Error_ResetFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone failed: {0}.
        /// </summary>
        public static string Error_CloneFailedFormat {
            get {
                return ResourceManager.GetString("Error_CloneFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No push target available. Configure a feed in Settings..
        /// </summary>
        public static string Error_NoPushTarget {
            get {
                return ResourceManager.GetString("Error_NoPushTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push failed: {0}.
        /// </summary>
        public static string Error_PushFailedFormat {
            get {
                return ResourceManager.GetString("Error_PushFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed: {0}.
        /// </summary>
        public static string Error_DeleteFailedFormat {
            get {
                return ResourceManager.GetString("Error_DeleteFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to discover repositories on Nexus: {0}.
        /// </summary>
        public static string Error_NexusDiscoverFailedFormat {
            get {
                return ResourceManager.GetString("Error_NexusDiscoverFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No raw repositories found on this Nexus server. Check connectivity and credentia.
        /// </summary>
        public static string Error_NoNexusRepos {
            get {
                return ResourceManager.GetString("Error_NoNexusRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed: {0}.
        /// </summary>
        public static string Error_ImportFailedFormat {
            get {
                return ResourceManager.GetString("Error_ImportFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import cancelled..
        /// </summary>
        public static string Error_ImportCancelled {
            get {
                return ResourceManager.GetString("Error_ImportCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local files not found. Please Import the version first..
        /// </summary>
        public static string Error_LocalFilesNotFound {
            get {
                return ResourceManager.GetString("Error_LocalFilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create VM failed: {0}.
        /// </summary>
        public static string Error_CreateVmFailedFormat {
            get {
                return ResourceManager.GetString("Error_CreateVmFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local image folder not found..
        /// </summary>
        public static string Error_LocalImageNotFound {
            get {
                return ResourceManager.GetString("Error_LocalImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete: {0}.
        /// </summary>
        public static string Error_DeleteLocalFailedFormat {
            get {
                return ResourceManager.GetString("Error_DeleteLocalFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating VM....
        /// </summary>
        public static string Status_CreatingVm {
            get {
                return ResourceManager.GetString("Status_CreatingVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}....
        /// </summary>
        public static string Status_CopyingFormat {
            get {
                return ResourceManager.GetString("Status_CopyingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}....
        /// </summary>
        public static string Status_DownloadingFormat {
            get {
                return ResourceManager.GetString("Status_DownloadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting archive....
        /// </summary>
        public static string Status_Extracting {
            get {
                return ResourceManager.GetString("Status_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import complete - click Create VM to spin up an instance..
        /// </summary>
        public static string Status_ImportComplete {
            get {
                return ResourceManager.GetString("Status_ImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating base snapshot....
        /// </summary>
        public static string Status_CreatingBaseSnapshot {
            get {
                return ResourceManager.GetString("Status_CreatingBaseSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying locale {0} (VM is booting)....
        /// </summary>
        public static string Status_ApplyingLocaleFormat {
            get {
                return ResourceManager.GetString("Status_ApplyingLocaleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM &quot;{0}&quot; created successfully..
        /// </summary>
        public static string Status_VmCreatedFormat {
            get {
                return ResourceManager.GetString("Status_VmCreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted local image &quot;{0}&quot;..
        /// </summary>
        public static string Status_DeletedLocalImageFormat {
            get {
                return ResourceManager.GetString("Status_DeletedLocalImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred:.
        /// </summary>
        public static string Error_UnexpectedFormat {
            get {
                return ResourceManager.GetString("Error_UnexpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error:.
        /// </summary>
        public static string Error_FatalFormat {
            get {
                return ResourceManager.GetString("Error_FatalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string Error_FatalTitle {
            get {
                return ResourceManager.GetString("Error_FatalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Manager failed to start:.
        /// </summary>
        public static string Error_StartupFormat {
            get {
                return ResourceManager.GetString("Error_StartupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        public static string Error_StartupTitle {
            get {
                return ResourceManager.GetString("Error_StartupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No VM backend is available on this machine..
        /// </summary>
        public static string Error_NoBackendMessage {
            get {
                return ResourceManager.GetString("Error_NoBackendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No VM Backend Found.
        /// </summary>
        public static string Error_NoBackendTitle {
            get {
                return ResourceManager.GetString("Error_NoBackendTitle", resourceCulture);
            }
        }
    }
}
